name: Deploy

on:
  push:
    branches: [ master ]  # 如果你的主分支是 main，就改成 main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /root/pump
            if [ -f deploy.sh ]; then
              bash deploy.sh
            else
              echo "部署脚本不存在"
              exit 1
            fi 